### ISSUE TITLE
Error running Spritz workflow (solved)

### ISSUE THREAD

**Issue by MiguelCos** [smith-chem-wisc/Spritz#180]
Hello, 

I am very interested on testing your workflow with our cancer samples.

I am trying to execute the workflow from the GUI to generate the protein sequence database + variants using SRA accessions but after some time the tool showed this error:
```
docker: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":" ...
See 'docker run --help'.
Error response from daemon: No such container: spritz
```

I am an ignorant in general regarding docker and containers so I am not sure where to start debugging. I would really appreciate if someone could offer any hints regarding the issue and how to solve it. I am attaching the whole workflow report.

Many thanks in advance!

[workflow_2020-08-04-17-12-13.txt](https://github.com/smith-chem-wisc/Spritz/files/5023058/workflow_2020-08-04-17-12-13.txt)

**Comment by acesnik** [comment]
Hi there, I'm glad you're interested in trying out the tool! Thank you for sharing that it didn't work on first try.

I haven't seen this error before, and it does look like a Docker issue. Could you please run `docker info` in CMD or Powershell and provide that information here?

Also, please make sure you have provided enough resources to Docker by going to the Docker Desktop app settings, e.g.:
![image](https://user-images.githubusercontent.com/16342951/89336492-145b8200-d65f-11ea-863a-0f472464d9eb.png)

And please check that the file sharing is available for all drives you intend to access, e.g.:
![image](https://user-images.githubusercontent.com/16342951/89336570-3523d780-d65f-11ea-9c47-df00ec481825.png)

(NB: If you have WSL2 enabled, the Docker Desktop resource page may not look the same.)

**Comment by MiguelCos** [comment]
Hello Anthony,

Many thanks for the quick feedback!

After opening this issue I continued to test on my own and I indeed realized that I haven't configured the File Sharing Resources correctly. I now have configured my Docker as shown in the images below.

![image](https://user-images.githubusercontent.com/33185213/89339586-b189db00-d69e-11ea-8e4a-bafc739edf71.png)

![image](https://user-images.githubusercontent.com/33185213/89339606-bc447000-d69e-11ea-8cfd-67e235b293ae.png)

After setting this up, the pipeline starts running but now this error is appearing, seemingly at step 17, when using the SRA accession suggested in the README. 

```
/bin/bash: line 1:  2100 Killed                  hisat2-build -p 12 data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic.fa data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic
[Tue Aug  4 19:13:43 2020]
Error in rule hisat_genome:
    jobid: 23
    output: data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic.1.ht2

RuleException:
CalledProcessError in line 34 of /app/rules/align.smk:
Command ' set -euo pipefail;  hisat2-build -p 12 data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic.fa data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic ' returned non-zero exit status 137.
  File "/app/rules/align.smk", line 34, in __rule_hisat_genome
  File "/usr/local/envs/spritz/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job hisat_genome since they might be corrupted:
data/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.karyotypic.1.ht2
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /app/.snakemake/log/2020-08-04T175816.199987.snakemake.log
(spritz) root@1b7dfc7bad7a:/app# exit
time="2020-08-04T22:02:43+02:00" level=error msg="error waiting for container: EOF"
Error response from daemon: Bad response from Docker engine
```
The complete workflow.txt is attached.
Some outputs are generated but not the `combined.spritz.snpeff.protein.withmods.xml.gz` file.

This is the info I get when executing`docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: 6NA6:GZBN:2ANC:ZLBP:BMWQ:K4LI:W3XC:MGIX:ETKL:TNVT:VMAH:3FKK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 51
  System Time: 2020-08-04T20:29:26.591331675Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Could this be related with my particular setup and/or computer resources. I am testing this now on a Ryzen 7 8-core processor + 16 GB RAM. 

Again, many thanks for taking the time. Really appreciated! Let me know if you need any additional information that might be useful.

Cheers,
Miguel

[workflow_2020-08-04-19-58-11.txt](https://github.com/smith-chem-wisc/Spritz/files/5024452/workflow_2020-08-04-19-58-11.txt)

**Comment by trishorts** [comment]
I experience intermittent crashes until I updated to WSL2.  I struggled to get that installed. But I think it was worth it. Here's my current system info. 


![image](https://user-images.githubusercontent.com/16841846/89348628-78d40c80-d672-11ea-8bc3-7bdfd9b1d45a.png)

**Comment by acesnik** [comment]
Miguel,

As Michael suggested, enabling WSL2 may help, since it's a new feature in Windows 10 that lets Docker run without using a virtual machine.

It looks like building the genome index failed during your latest run, which may be due to RAM allocation issues. Your settings in Docker Desktop look great, but the `docker info` output shows ~2 GB of RAM allocated. You may need to restart Docker or restart your computer to get Docker to use the whole 16 GB.

Hope that helps!

Anthony

**Comment by MiguelCos** [comment]
Hello all,

Just wanted to come back and let you know that I managed to execute the workflow thoroughly for constructing a Human variants database, both using your suggested SRA ID and one of my interest. I also already ran a search with MetaMorpheus and found some variant peptides.

I did that after installing WSL2, but I did experience some crashes even after having WSL2 installed. I just kept trying and the workflow ran through, with no apparent modification to my knowledge. The only think I can recall is that I was using a system monitor initially to check the CPU / RAM usage. I wasn't using any system monitor when the workflow(s) went through. 

I now have some questions on setting up the search for quantitation in MetaMorpheus but I would post them on the correspondent repo.

Many thanks for the support!

Miguel

**Comment by trishorts** [comment]
That's awesome. Thanks for the update.

I want you to know how much we value your feedback and input. It's the most important thing in making Spritz more stable, more functional and more useful.

Also, we have some new updates to Spritz that should be added shortly. Please keep an eye out for those. They should improve your experience.

We have also worked to make sure that MetaMorpheus can reveal the variant peptides that you work so hard to create a database for. If we can help make MetaMorpheus work better for you, please tell us. MetaMorpheus provides many avenues for communication (email, github and slack).
