### ISSUE TITLE
Error in rule reference_protein_xml

### ISSUE THREAD

**Issue by animesh** [smith-chem-wisc/Spritz#201]
Running Spritz on Windows 10 and it seems to fail with this message in [workflow_2021-01-24-13-22-23.txt](https://github.com/smith-chem-wisc/Spritz/files/5878531/workflow_2021-01-24-13-22-23.txt) although the GUI seems to be still on (screenshot below shows "Run workflow!" button in pressed state?)
![image](https://user-images.githubusercontent.com/21457/105960851-133f6680-607e-11eb-82f5-7a6a34fb82ed.png)
What could be a way out of it, any help will be much appreciated 👍🏼

**Comment by trishorts** [comment]
there is one known issue involving a missing reference and I don't know if that is the trouble here. Anthony said he would get that looked at this week. At this point, I suggest just restarting the job. Spritz should pick up where it left off and not try to redo what has already been done. Let us know if this works. Also, you could post or send us the log file. That may be more illuminating.

**Comment by animesh** [comment]
Thanks @trishorts for insight 👍🏼 as report, "Run Workflow!" button is not functioning so to re-run, do i need to close the GUI and restart the whole process and it will pick up from where it crashed or there is another way? Three latest log files are attached (
[combined.sorted.grouped.marked.log](https://github.com/smith-chem-wisc/Spritz/files/5886324/combined.sorted.grouped.marked.log)
[Homo_sapiens.GRCh38.97.spritz.log](https://github.com/smith-chem-wisc/Spritz/files/5886325/Homo_sapiens.GRCh38.97.spritz.log)
[combined.sorted.log](https://github.com/smith-chem-wisc/Spritz/files/5886326/combined.sorted.log)

**Comment by trishorts** [comment]
yes. close the gui. no problem. just load the same files at the start and set up your run the same way and hit go.

thanks for the files. we'll have a look

**Comment by trishorts** [comment]
it's still possible that you run into the same problem. we need to accept the latest pull request and make a new release. but you should know pretty quick if the job fails again.

**Comment by acesnik** [comment]
I was able to reproduce the error in `reference_protein_xml`, and updating mzLib does allow Spritz to make it past this step again. I made a new release with the updated mzLib library. You should be automatically prompted to install it next time you open Spritz. Hope that helps!
