### ISSUE TITLE
Error in rule build_transfer_mods

### ISSUE THREAD

**Issue by llniu** [smith-chem-wisc/Spritz#203]
Running Spritz in terminal with the following config parameters:

```
sra: [SRR629563] 
fq: [] 
sra_se: [] 
fq_se: [] 
analysisDirectory: [AnalysisFolder] 
species: "Homo_sapiens"
genome: "GRCh38"
release: "100"
organism: "human" 
analyses: [isoform,variant]
spritzversion: "0.2.3"
```

and found "Error in rule build_transfer_mods":

```
    jobid: 27
    output: TransferUniProtModifications/TransferUniProtModifications/bin/Release/netcoreapp3.1/TransferUniProtModifications.dll
    log: data/TransferUniProtModifications.build.log (check log file(s) for error message)
    shell:
        (cd TransferUniProtModifications && dotnet restore && dotnet build -c Release TransferUniProtModifications.sln) &> data/TransferUniProtModifications.build.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by llniu** [comment]
The script skipped the error message and continued to run as I am typing this message.

**Comment by acesnik** [comment]
Could you share the file `data/TransferUniProtModifications.build.log`?

If you are running it on Mac, do you have `dotnet` installed? https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.403-macos-x64-installer

**Comment by llniu** [comment]
Yes I installed dotnet but it seems there are issues executing it. 

The log content is "/bin/bash: dotnet: command not found"

When I type `dotnet info` in terminal, I got below error messages:

```
(base) SUN1012693:Spritz jpx667$ dotnet info
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-info does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by llniu** [comment]
es I installed dotnet but it seems there are issues executing it.

The log content is "/bin/bash: dotnet: command not found" 
I set interactive shell to /bin/bash instead of the default login shell. Can this be the problem?

When I type dotnet info in terminal, I got below error messages:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-info does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by acesnik** [comment]
Hmm, I think it installs to `/usr/local/bin` by default on Mac. Is that in your PATH if you check with `echo $PATH`?

**Comment by acesnik** [comment]
If you're running Windows or Linux, it should be set up automatically by `conda`.

**Comment by acesnik** [comment]
If `/usr/local/bin/` is on your PATH environment variable (echoed by `echo $PATH`), I'd recommend downloading and running the dotnet installer linked above to see if that helps.

**Comment by llniu** [comment]
Adding .NET to PATH solved the problem :) Thanks! Reference: https://docs.microsoft.com/en-us/dotnet/core/install/macos
