### ISSUE TITLE
Same issue as #199 with updated mzLib

### ISSUE THREAD

**Issue by stsour** [smith-chem-wisc/Spritz#213]
Hello @acesnik !

I would like to reopen this issue where execution halts at Transfer UniProtModifications step. I have just cloned the current Spritz release into my CENTOS server home drive. This is an access-protected server and I went through all the steps for offline computing. Everything worked until step 11. 

I am running into the exact same issue as Stanley80, but I presume that the mzLib update is included in the latest release? For some reason, this is not solving the problem for me. 

Would appreciate some assistance! Thanks.

_Originally posted by @stsour in https://github.com/smith-chem-wisc/Spritz/issues/199#issuecomment-848287324_

**Comment by acesnik** [comment]
Hi there, thank you for posting this issue. Have you tried using the HEAD of the main branch, rather than the release? It looks like this may have been due to [this change](https://github.com/smith-chem-wisc/Spritz/compare/0.2.4...master#diff-d95c74e3247296b1f8f08226e52d0d902a3f8cef67e5e7017625fa6c73e5a1cdR46). I'll make a release now of the current HEAD, since that's an important change.

If that doesn't solve the issue, I'll try to check it out sometime this month. (This is a software project from my former group.)

-AC

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/Spritz/releases/tag/0.2.5

**Comment by stsour** [comment]
Hi Anthony. Thanks for getting back to me!
I am going to try the link you sent now and will let you know how it goes.

**Comment by stsour** [comment]
Hey, sorry for the delayed response, the cluster I work on was undergoing maintenance. 

I tried with the updated 0.2.5 release, but it did not work and was throwing the same error. I was getting the error at different steps in the processing, though. 

I checked the file you referred to above and the changes you made were not actually there, so I manually added them. Running again now, will keep you updated. 

Also, understood that this is your previous group - might you be able to refer me to a current member in case more questions come up? 


Lastly, I have one question I hope you can answer. Am I able to process say a dozen RNA-seq data files simultaneously if the output directory and fq filenames are unique? Or will snakemake have issues with this? 

Thank you very much! 
ST

**Comment by acesnik** [comment]
I'm still point on the project for now, and will try to continue maintaing it. Maybe @trishorts knows if anyone else wants to get involved.

Could you let me know which file didn't pop up with the 0.2.5 setup?

Yes, you should be able to process 12 files at once, and they will produce one final database with variants and/or isoforms. If they belong to different experiments and you want multiple databases (e.g. for different species), you'll need to run Spritz separately on those batches.

**Comment by stsour** [comment]
I was referring to the change in TransferUniProtModifications/TransferUniProtModifications/TransferUniProtModifications.cs that you mention above. This was an error on my part though, I apologize!

Either way though, the fix does not seem to work, I keep getting the same error with TransferUniProtModifications. 

I would like to process multiple files at once and generate separate databases. Do I need to copy over Spritz into a new directory for each? Or is there a way I could tell the program where to look for config.yaml?

**Comment by acesnik** [comment]
Sorry for the delay! I finally figured out this error in TransferUniProtMods, and it'll be integrated in the next release.

At the moment, Spritz generates one combined database for all the input files. I'd recommend running them sequentially. This can be done by moving all files starting with `combined` from the results folder to an external folder. Let me know if you need more help with doing that.

Just made a new feature request for generating separate databases for each input. https://github.com/smith-chem-wisc/Spritz/issues/216

**Comment by acesnik** [comment]
I believe the issue with TransferUniProtModifications is solved in https://github.com/smith-chem-wisc/Spritz/pull/211. Please give this a try with the most recent version of Spritz, and feel free to reopen or open a new issue report if you encounter this again!
