### ISSUE TITLE
Possible install problem of STAR

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/Spritz#28]
The /CMD/bin/Debug/STAR file is empty after the first time setup. (Both in Orion or LEI)
Delete the STAR directory, then setup again will install STAR successfully.
Related to STARWrapper.cs Line 184. 

A bug only in LEI. a  /CMD/bin/Debug/bin directory contain something in /CMD/bin/Debug/bedops are not   remove somehow

**Comment by acesnik** [comment]
Could you try a fresh setup and see if the bug persists? Rename or delete
the Debug directory, and then build and run the setup again.

**Comment by lonelu** [comment]
This issue is just proved to relate with the interruption of install GATK before. But could be a possible
