### ISSUE TITLE
Design and make a GUI

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/Spritz#32]

**Comment by lonelu** [comment]
I think we should build the GUI kind of follow MetaMorpheus. Several advantages:
1. Consistent for users to use both software. They look the similar and work similar. 
2. Easy to build and maintain by ourselves. And already prove to be robust.
3. .....

**Comment by acesnik** [comment]
Agreed!

I think it could be as simple as a data frame on left for FASTQ/SRA/BAM input, and on the right a tab structure for workflows, like Search and GPTMD in MM, above an output file tree like MM. Output should include output files as they pop out under the program being run. 

Could even capture the stdout and stderr in LOG files and display the live output in a rich text box.

**Comment by acesnik** [comment]
From @lonelu! ![image](https://user-images.githubusercontent.com/16342951/35358260-9b0c23e8-011b-11e8-9344-48464699ab8a.png)

**Comment by acesnik** [comment]
Could you add a workflow tab for `Setup`?

**Comment by acesnik** [comment]
This is beautiful! Nice work carrying over the MetaMorpheus design!

**Comment by lonelu** [comment]
I am thinking about a Setup (Software Maintain) near 'Help'. We don't always Setup.

**Comment by acesnik** [comment]
- [ ] Remove Genome Fasta and Gene Set boxes, since those are downloaded automatically
- [ ] Add a box to list SRAs; these will be written to the commandline as a comma-separated list
- [ ] Focus in on the sample specific database workflow
- [ ] Take in the snpEff.config information regarding genomes and gene sets as a dictionary (e.g. key: GRCh38.81, value: tuple with genome fasta URL and GTF gene set URL)
- [ ] Delete setup menu
- [ ] Make setup a popup box that appears after checking whether the setup was successful. Maybe use a text file in the build directory to note whether setup was successful. Or maybe check that all the executables are there (see Test/WrapperIntegrationTests.InstallTest() for an example of how to check all the folders; I suppose we could make that another method).

**Comment by acesnik** [comment]
- [ ] Enable specifying in the FASTQs box whether the sequences belong in --fq1 or --fq2 for paired-end reads. Will also need to specify multiple sets of paired-end reads.

**Comment by acesnik** [comment]
- [ ] For SRAs, after downloading the FASTQs and populating the `List<string[]>` list of fastq files, display those fastq files in the FASTQs box in the GUI.
- [ ] Start the `everythingrunner` on a new thread, so we can manipulate the program while it's running for hours.

**Comment by acesnik** [comment]
This is looking great! I'll transfer the remaining stuff to new, smaller issues.
