### ISSUE TITLE
Validation of fasta files before adding to genome fasta or protein fasta lists

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/Spritz#54]
Important for the GUI. We can use the BioDotNet framework for this:
1. Load the fasta
2. Check the alphabet

**Comment by lonelu** [comment]
I will take care of this one.

**Comment by acesnik** [comment]
Okay!

**Comment by lonelu** [comment]
try
                    {
                        var parser = new FastAParser();
                        parser.Alphabet = Alphabets.AmbiguousDNA;
                        var test = parser.Parse(filepath).First();
                    }
                    catch (Exception)
                    {
                        MessageBox.Show("The fasta is protein fasta", "Error database", MessageBoxButton.OK);
                        break;
                    }          

I use the Bio.IO.FastA, and the code works. But the parser.Parse() will consume RAM and time.
